DROP database IF EXISTS QUANLYFRESHER;
CREATE DATABASE IF NOT EXISTS QUANLYFRESHER;
USE QUANLYFRESHER;
 
DROP TABLE IF EXISTS TRAINEE;
CREATE TABLE TRAINEE
(
   TRAINEE_ID                TINYINT AUTO_INCREMENT PRIMARY KEY,
   FULL_NAME                 NVARCHAR(30) NOT NULL,
   BIRTH_DATE                DATE NOT NULL,
   GENDER                    ENUM('MALE','FEMALE','UNKNOWN'),
   ET_IQ                     TINYINT CHECK ((ET_IQ >= 0) AND (ET_IQ <= 20)) NOT NULL,
   ET_GMATH                  TINYINT CHECK ((ET_GMATH >= 0) AND (ET_GMATH <= 20)) NOT NULL,
   ET_ENGLISH                TINYINT CHECK ((ET_ENGLISH >= 0) AND (ET_ENGLISH <= 50)) NOT NULL,
   TRAINING_CLASS            CHAR(10) NOT NULL,
   EVALUATION                NVARCHAR(200)
);




